name: 'Run luacheck with reviewdog'
description: '🐶 Run luachekc with reviewdog on pull requests to improve code review experience.'
author: 'Puria 💣 Nafisi Azizi <puria@dyne.org>'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
  workdir:
    description: 'Working directory relative to the root directory.'
    default: '.'
  ### Flags for reviewdog ###
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: 'Reporter of reviewdog command [github-pr-check,github-pr-review].'
    default: 'github-pr-check'
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is added.
    default: 'added'
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false]
      Default is `false`.
    default: 'false'
  reviewdog_flags:
    description: 'Additional reviewdog flags'
    default: ''
  ### Flags for luacheck ###
  luacheck_flags:
    description: 'luacheck flags. (luacheck --format plain <luacheck_flags> .)'
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'

# https://actions-cool.github.io/github-action-branding/
branding:
  icon: 'moon'
  color: 'green'
